# VictoriaMetrics metrics store for the otel gateway, see victoria-metrics/README.md in the observability repository
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
  namespace: ${nameSpace}
spec:
  interval: 5m0s
  timeout: 10m
  targetNamespace: ${nameSpace}
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
      remediateLastFailure: true
  chart:
    spec:
      chart: ./victoria-metrics/victoria-metrics
      sourceRef:
        kind: GitRepository
        name: observability
        namespace: ${nameSpace}
  valuesFrom:
    - kind: ConfigMap
      name: victoria-metrics-values
      valuesKey: values.yaml
      optional: true
  values:
    victoria-metrics-k8s-stack:
      vmsingle:
        ingress:
          enabled: true
          ingressClassName: ${victoriaMetricsIngressClassName:=nginx} # Set victoriaMetricsIngressClassName to openshift-default on crc
          annotations:
            cert-manager.io/cluster-issuer: local-ca-issuer
          hosts:
            - victoria-metrics.${dnsSuffix}
          tls:
            - secretName: victoria-metrics-tls
              hosts:
                - victoria-metrics.${dnsSuffix}
