namespace: default
serviceAccount: default
node: ""
secContext: ""

image:
  repository: paulcarltondae/debug-pod
  tag: 0.1.0
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
    ephemeralStorage: 2Gi

tmpSizeLimit: 1Gi
  