apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: observability
  namespace: ${nameSpace}
spec:
  interval: 1h
  url: https://${observabilityGitHubServer}/${observabilityGitHubOrg}/${observabilityGitHubRepo}.git
  secret:secretRef:
    name: observability-git-token
  ref:
    branch: ${observabilityBranch}
