apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: observability
  namespace: ${nameSpace}
spec:
  interval: 5m
  url: https://${observabilityGitHubServer:=${GitHubServer}}/${observabilityGitHubOrg}/${observabilityGitHubRepo}.git
  secretRef:
    name: observability-git-token
  ref:
    branch: ${observabilityBranch}
