apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: vault
  namespace: vault
spec:
  host: vault.{{ .Values.dnsSuffix }}
  path: /
  to:
    kind: Service
    name: vault
  port:
    targetPort: 8200
  tls:
    termination: edge
