---
# Copy of the flux-system cluster-config ConfigMap for the app's namespace, values are quoted as ConfigMap data must be
# strings
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: ${nameSpace}
data:
  clusterType: "${clusterType}"
  kindCluster: "${kindCluster:=false}"
  kubeletInsecureTLS: "${kubeletInsecureTLS:=false}"
  storageClass: "${storageClass:=}"
  clusterName: "${clusterName}"
  dnsSuffix: "${dnsSuffix}"
  clusterIP: "${clusterIP}"
  scmType: "github"
  registry: "${registry}"
  GitHubServer: "${GitHubServer}"
  GitHubOrg: "${GitHubOrg}"
  GitHubRepo: "${GitHubRepo}"
  GitHubBranch: "${GitHubBranch:=main}"
  globalGitHubOrg: "${globalGitHubOrg}"
  globalGitHubRepo: "${globalGitHubRepo}"
  globalGitHubBranch: "${globalGitHubBranch}"
  userEmail: "${userEmail}"
  vault_url: "${vault_url}"
  commitUser: "${commitUser}"
  mirrorRegistry: "${mirrorRegistry:=}"
  imagePullSecretName: "${imagePullSecretName:=}"
  proxy: "${proxy:=false}"
  certs: "${certs:=false}"
