apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: ${nameSpace}
spec:
  interval: 5m0s
  ref:
    branch: main
  secretRef:
    name: github-repo-read-credentials
  url: https://${GitHubServer}/${GitHubOrg}/${GitHubRepo}.git
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: mac-k8s-config
  namespace: ${nameSpace}
spec:
  interval: 5m0s
  ref:
    branch: ${globalGitHubBranch}
  secretRef:
    name: github-repo-read-credentials
  url: https://${GitHubServer}/${globalGitHubOrg}/${globalGitHubRepo}.git

