apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-source-${appName}
  namespace: ${nameSpace}
spec:
  interval: 1m0s
  retryInterval: 30s
  timeout: 30s
  dependsOn:
    - name: ${dependsOnName}
      namespace: ${dependsOnNs}
  path: ./local-cluster/apps/${appName}/source
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: mac-k8s-config
  postBuild:
    substitute:
      nameSpace: ${nameSpace}
      appName: ${appName}
      # config values from apps.yaml
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
