---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: ${namespace}
data:
  clusterType: ${CLUSTER_TYPE:-k8s}
  clusterName: ${CLUSTER_NAME}
  dnsSuffix: ${local_dns}
  clusterIP: ${CLUSTER_IP}
  scmType: github
  registry: ${REGISTRY}
  GitHubServer: ${GITHUB_SERVER}
  GitHubOrg: ${GITHUB_MGMT_ORG}
  GitHubRepo: ${GITHUB_MGMT_REPO}
  GitHubBranch: ${GITHUB_MGMT_BRANCH}
  globalGitHubOrg: ${GITHUB_GLOBAL_CONFIG_ORG}
  globalGitHubRepo: ${GITHUB_GLOBAL_CONFIG_REPO}
  globalGitHubBranch: ${global_config_branch}
  userEmail: ${USER_EMAIL}
  vault_url: ${VAULT_ADDR}
  commitUser: ${GITHUB_USER}
