apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - url(https://raw.githubusercontent.com/${GITHUB_GLOBAL_CONFIG_ORG}/${GITHUB_GLOBAL_CONFIG_REPO}/${global_config_branch}/local-cluster/core/flux/${FLUX_VERSION}/gotk-components.yaml)