apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-node
  namespace: ${nameSpace}
spec:
  interval: 5m
  targetNamespace: ${nameSpace}
  chart:
    spec:
      chart: ./otel/node/otel-node
      sourceRef:
        kind: GitRepository
        name: observability
        namespace: ${nameSpace}
  valuesFrom:
    - kind: ConfigMap
      name: cluster-config
      valuesKey: clusterType
      targetPath: clusterType
    - kind: ConfigMap
      name: cluster-config
      valuesKey: clusterName
      targetPath: clusterName
    - kind: ConfigMap
      name: otel-node-values
      valuesKey: values.yaml
      optional: true
  values:
    otelNamespace: ${nameSpace}
