apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-node
  namespace: ${nameSpace}
spec:
  interval: 5m
  targetNamespace: ${nameSpace}
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true

  chart:
    spec:
      chart: ./otel/node/otel-node
      sourceRef:
        kind: GitRepository
        name: observability
        namespace: ${nameSpace}
  valuesFrom:
    - kind: ConfigMap
      name: otel-node-values
      valuesKey: values.yaml
      optional: true
  values:
    otelNamespace: ${nameSpace}
    clusterType: ${clusterType}
    clusterName: ${clusterName}
    targets: # Set otelNewRelic, otelSplunk, otelVictoriaMetrics and otelLoki in the otel app config in resource-descriptions/apps.yaml
      newrelic:
        enabled: ${otelNewRelic:=true}
      splunk:
        enabled: ${otelSplunk:=true}
      victoriametrics:
        enabled: ${otelVictoriaMetrics:=false}
      loki:
        enabled: ${otelLoki:=false}
