apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: newrelic-key
  namespace: ${nameSpace}
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: newrelic-key
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: apps/otel/newrelic-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: splunk-hec-token
  namespace: ${nameSpace}
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: splunk-hec-token
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: apps/otel/splunk-hec-token
