{{- $repository := printf "%s/external-secrets/external-secrets" (include "addon.registry" (list . "oci.external-secrets.io")) -}}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  chart:
    spec:
      chart: external-secrets
      version: 0.12.1
      sourceRef:
        kind: HelmRepository
        name: external-secrets
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
    crds: CreateReplace
  interval: 5m0s
  timeout: 5m
  values:
    image:
      repository: {{ $repository }}
    imagePullSecrets: {{- include "addon.imagePullSecrets" . | nindent 6 }}
    # The controller accesses the external secret stores
    extraEnv: {{- include "addon.proxyEnv" . | nindent 6 }}
    extraVolumes: {{- include "addon.caVolumes" . | nindent 6 }}
    extraVolumeMounts: {{- include "addon.caVolumeMounts" . | nindent 6 }}
    webhook:
      image:
        repository: {{ $repository }}
      imagePullSecrets: {{- include "addon.imagePullSecrets" . | nindent 8 }}
    certController:
      image:
        repository: {{ $repository }}
      imagePullSecrets: {{- include "addon.imagePullSecrets" . | nindent 8 }}
