apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
        - name: manager
          volumeMounts:
            - name: cert-volume
              mountPath: /etc/ssl/certs/root-ca.crt
              subPath: root-ca.crt
              readOnly: false
      initContainers:
        - name: init-source-controller-certs
          image: debian
          command:
            ["sh", "-c", 'echo "$TRUSTED_CERT" > /var/tmp/root-ca.crt']
          env:
            - name: TRUSTED_CERT
              valueFrom:
                configMapKeyRef:
                  name: root-ca
                  key: root-ca.crt
          volumeMounts:
            - name: cert-volume
              mountPath: /var/tmp
      volumes:
        - name: cert-volume
          emptyDir: {}