---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${appName}-config
  namespace: ${nameSpace}
data:
  observabilityBranch: ${observabilityBranch:=main}
  observabilityGitHubOrg: ${observabilityGitHubOrg:=pc-dae}
  observabilityGitHubRepo: ${observabilityGitHubRepo:=observability}
  observabilityGitHubServer: ${observabilityGitHubServer:=${GitHubServer}}
